version: "3.7"

services:

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "30001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test
      PGADMIN_DEFAULT_PASSWORD: test
    logging:
      driver: none

  db:
    image: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: bookstore
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "55321:5432"
    volumes:
      - lab4_pgdb:/var/lib/postgresql3/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  lab4_pgdb:
